### PR TITLE
PAIN_Vid[21-22] #25

### PR DESCRIPTION
**Pull request by Vanditha07**
### Related Issue 
PAIN [vid 21-22] #25

### Info about the related issue 
Extracting 50 RGB images of the baby's facial expressions from each video. Later, convert the 50 RGB images to gray scale images. Classify the total 200 images into 4 folders as per the facial expressions.

- [x] DevIncept Participant

- [x] Contributor

Closes: #25 

### Describe the add-ons or changes you've made
Used opencv to extract 50 images each from videos 21-22 and converted them to grayscale. Later, classified those into four folders based on the expressions.

### Type of change
What sort of change have you made:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?
The Images were verified before uploading. 

### Checklist:
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Kindly follow the PR template given. You can edit it using edit option here at your PR comment. Also make sure to add your issue number in your PR template. This is to know you as a devincept participant. Kindly do that. @Vanditha07

**Review by SamarthMR — APPROVED** [review]

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Hey, can you elaborate your README more? It looks like a skelton. Provide description of the issue you worked on.  Add goal, purpose, workflow. Conclusion should be briefer and precise of all the understandings given above. Also include 1 image file each from 3 categories provided. Add them in output section in README.md file. 
Once you do it, we shall merge the PR. @Vanditha07

**Review by SamarthMR — COMMENTED** [review]
Kindly elaborate more on your README file inside your name folder.

**Review by SamarthMR — APPROVED** [review]
Good work @Vanditha07 🎉👏🏻

**Pull request merged**
