### PR TITLE
All remaining Pain videos (RGB only)

### PR DESCRIPTION
**Pull request by iharshidas**
Due to large size, this directory consists of only the RGB images. Will soon create another PR for their respective Grayscale images (tomorrow EOD)

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Kindly follow the proper PR template mentioned with issue number. You can't do multiple PR's for single issue. Create PR only when it's ready completely in a single PR. Point to note, tomorrow is the last day to merge the PR's. Do it on time so that your efforts don't go wasted. @iharshidas

**Comment by prathimacode-hub** [comment]
By the way, where is your issue? I don't think you had been assigned to any issue. This stands invalid. You can only work on an issue when its assigned.

**Comment by iharshidas** [comment]
I am new to open-source. I saw a message in Slack that if anyone is able to extract frames from all videos at once, then they can share that. So should I instead work on open issues?
Because this directory has all the remaining pain videos' frame extracted.

**Comment by prathimacode-hub** [comment]
First thing to do express interest on issue and get it assigned before you work. Most important go through the contributing guidelines and readme file of the project. Then work on it and create a single PR for complete project. But the thing is deadline to close the PR is only tomorrow. If you  couldn't do it right in proper project structure by tomorrow evening, you can go ahead with expressing your interest on issue you would like to work on. So let me know your plan. @iharshidas

**Comment by iharshidas** [comment]
Okay. I will work on the open issues then and create a new PR. Thank you

**Comment by prathimacode-hub** [comment]
> Okay. I will work on the open issues then and create a new PR. Thank you

first get one issue assigned to you. @iharshidas

**Comment by SamarthMR** [comment]
Kindly go through the guidelines and follow the templates for getting an issue assigned first and then create PR after completing your work by following the template. Make sure you have committed to the Main branch and not to any of your own branch @iharshidas.

**Comment by SamarthMR** [comment]
As this PR is invalid, I'm closing this PR.

**Pull request closed without merging**
