### PR TITLE
NALIN_VERMA_PAIN_VID[23-24]

### PR DESCRIPTION
**Pull request by MrNobody09**
Related Issue - AI/ML in healthcare
Info about the related issue
There are various cases where there is birth of premature babies. Also there are issues with new born babies with their health. With this project we try to solve the problem using technology and some of our insights

√DevIncept Participant

√Contributor

Closes: #26 

Describe the changes you've made
Give a clear description of what modifications you have made
Extracting colored and gray images of the baies using opencv and classifying them

Type of change
What sort of change have you made: Feature change/update

Bug fix (non-breaking change which fixes an issue)
√New feature (non-breaking change which adds functionality)
Code style update (formatting, local variables)
Breaking change (fix or feature that would cause existing functionality to not work as expected)
This change requires a documentation update

How Has This Been Tested?
Describe how have you verified the changes made
I tested it using my code and verifying the results that were required.

Checklist:
√My code follows the guidelines of this project.
√I have performed a self-review of my own code.
√I have commented on my code, particularly wherever it was hard to understand.
√I have made corresponding changes to the documentation.
√My changes generate no new warnings.
√I have added tests that prove my fix is effective or that my feature works.
√Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
No PR template, no project details, no issue number. Kindly add up these things to check on with the PR. @MrNobody09

**Comment by MrNobody09** [comment]
Sir I have made the changes , is it okay or should I have to add more
details?

**Comment by SamarthMR** [comment]
Can you add 3-4 output images screenshots in your Readme.md Screenshots section in the file instead of telling "The images in the Image_Dataset folder are the Output of my code" @MrNobody09.
So that it looks good to understand everything that you have done just by going through the Readme file.

**Comment by MrNobody09** [comment]
> Can you add 3-4 output images screenshots in your Readme.md Screenshots section in the file instead of telling "The images in the Image_Dataset folder are the Output of my code" @MrNobody09.
> So that it looks good to understand everything that you have done just by going through the Readme file.

done sir

**Review by SamarthMR — APPROVED** [review]
Great work!! 👏🎉 Everything is looking very presentable and neat. You have very fast grasping and completed your work by the deadline. Congrats on making your PR.
Hope you are doing good now. Take care of your health. All the Best for your future 😃👍🏻 @MrNobody09

**Pull request merged**
