### PR TITLE
Colored and gray images extraction using opencv-python

### PR DESCRIPTION
**Pull request by divyaachoudharyy**
I have written code to extract colored and gray images of baby who are preterm born babies. Do have a look and let me know If I need to change anything.

issue #21

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Kindly follow the PR template given so that we can check on with the PR. @divyaachoudharyy

**Comment by divyaachoudharyy** [comment]
## Related Issue 

- Extracting colored and gray images of the children using opencv at one go or in one single code.

- [ ] DevIncept Participant
- [ ] Contributor

Closes: issue#21 

### Describe the add-ons or changes you've made

My code is quite easy to understand. I have seperately made two folders to store colored and gray images so that it may avoid confusion and also reduces the work. 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I have tested it using jupyter notebook and also was careful while seperating the child's images into three different folders.

## Checklist:

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

**Comment by prathimacode-hub** [comment]
Are you a devincept participant? @divyaachoudharyy

**Comment by SamarthMR** [comment]
Any PR if it's open for more than 5-7 days, and if the work has been kept pending will be discarded/closed.

Because you have created PR long back and has not updated anything since then, it's against the Open-source. Unfortunately your PR has been closed @divyaachoudharyy.

**Pull request closed without merging**
