### PR TITLE
Pain video[11-12]

### PR DESCRIPTION
**Pull request by vishvarana**
Related Issue - AI/ML in healthcare
Info about the related issue 
There are various cases where there is birth of premature babies. Also there are issues with new born babies with their health. With this project we try to solve the problem using technology and some of our insights

 √DevIncept Participant

 √Contributor

Closes: #17 

Describe the changes you've made
Give a clear description of what modifications you have made
Extracting colored and gray images of the baies using opencv and classifying them

Type of change
What sort of change have you made: Feature change/update

 Bug fix (non-breaking change which fixes an issue)
 √New feature (non-breaking change which adds functionality)
 Code style update (formatting, local variables)
 Breaking change (fix or feature that would cause existing functionality to not work as expected)
 This change requires a documentation update

How Has This Been Tested?
Describe how have you verified the changes made
I tested it using my code and verifying the results that were required.

Checklist:
 √My code follows the guidelines of this project.
 √I have performed a self-review of my own code.
 √I have commented on my code, particularly wherever it was hard to understand.
 √I have made corresponding changes to the documentation.
 √My changes generate no new warnings.
 √I have added tests that prove my fix is effective or that my feature works.
 √Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
In README.md, elaborate your description, and in screenshots, add 1 image path link each from "No-Mild", "Severe" and "Moderate".

Kindly do this addups. @vishvarana

**Comment by prathimacode-hub** [comment]
Kindly do the changes, last date to merge PR's is today. @vishvarana

**Comment by vishvarana** [comment]
Will do right away

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
You haven't done the changes yet. Image links haven't been added in README.md file as asked. Kindly do that. @vishvarana

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. This was an amazing start you had done in this repo. Welcome to this repo. Your efforts are appreciated. Good to have you here. ✔👏🙌@vishvarana

**Pull request merged**
